# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-dotnet@v3
    
    - name: Download tzdata
      run: wget 'https://www.iana.org/time-zones/repository/tzdata-latest.tar.gz'
      
    - name: Extract tzdata
      run: tar -xzf tzdata-latest.tar.gz africa antarctica asia australasia etcetera europe factory northamerica southamerica

    - name: Compile timezone data
      run: sudo zic -d tzdata_compiled/ africa antarctica asia australasia etcetera europe factory northamerica southamerica

    - name: Create .NET project
      run: dotnet new classlib -n TimeZoneData

    - name: Add timezone data to project
      run: cp tzdata_compiled/* TimeZoneData/

    - name: Pack NuGet package
      run: |
        cd ./TimeZoneData
        dotnet pack --output ./nupkgs /p:PackageVersion=1.0.0 /p:PackageId=YourPackageName
    
    - name: Upload NuGet Package
      uses: actions/upload-artifact@v3
      with:
        name: YourPackageName
        path: ./nupkgs/YourPackageName.1.0.0.nupkg
